/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatsoldIndexRouteImport } from './routes/chatsold/index'
import { Route as ChatsIndexRouteImport } from './routes/chats/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsoldIndexRoute = ChatsoldIndexRouteImport.update({
  id: '/chatsold/',
  path: '/chatsold/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsIndexRoute = ChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chats/': typeof ChatsIndexRoute
  '/chatsold/': typeof ChatsoldIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chats': typeof ChatsIndexRoute
  '/chatsold': typeof ChatsoldIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chats/': typeof ChatsIndexRoute
  '/chatsold/': typeof ChatsoldIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chats/' | '/chatsold/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chats' | '/chatsold'
  id: '__root__' | '/' | '/chats/' | '/chatsold/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatsIndexRoute: typeof ChatsIndexRoute
  ChatsoldIndexRoute: typeof ChatsoldIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatsold/': {
      id: '/chatsold/'
      path: '/chatsold'
      fullPath: '/chatsold/'
      preLoaderRoute: typeof ChatsoldIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats/': {
      id: '/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof ChatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatsIndexRoute: ChatsIndexRoute,
  ChatsoldIndexRoute: ChatsoldIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
